<?php
/**
 * Created by PhpStorm.
 * User: wuhanchu
 * Date: 15/12/20
 * Time: 10:42
 */

namespace Addons\GroupBuy\Controller;


class GroupBuyPartyController extends BaseController
{
    /**
     * init
     */
    function _initialize()
    {
        parent::_initialize();

        // 配置模型
        $this->model = $this->getModel('groupbuy_party');
    }

    /**
     * 显示列表
     */
    public function lists()
    {
        $this->assign('add_button', 0);
        $this->assign('del_button', 0);
        $this->assign('check_all', 0);

        parent::lists(); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $model
     * @param int $page
     * @param string $order
     * @return mixed
     */
    public function _get_model_list($model = null, $page = 0, $order = 'id desc', $showPrivilege = true)
    {
        $model || $model = $this->model;
        unset($_GET["openid"]);
        unset($_REQUEST["openid"]);

        $list_data = parent::_get_model_list($model, $page, $order);
        $list_data ['list_data'] = $this->convertListField($list_data ['list_data'], 'openid', 'phone', 'student', 'openid');
        $list_data ['list_data'] = $this->convertListField($list_data ['list_data'], 'openid', 'openid', 'student', 'openid', "name");
        if ($showPrivilege) {
            $list_data ['list_data'] = $this->addListGroupBuyField($list_data ['list_data']);
        }

        // 重新设置显示效果
        $this->assign('add_button', 0);
        $this->assign('del_button', 0);
        $this->assign('check_all', 0);

        // 修正其他查询
        return $list_data;
    }

    /**
     * 退款
     */
    public function refund()
    {
        $_POST["id"] = $_GET["id"];;
        $_POST["is_refund"] = 1;
        $this->saveModel($this->model[name]);
        $this->lists();
    }

    /**
     *  团购的相关参与人
     */
    function getPartyList()
    {
        // 取得团购ID
        $groupBuyId = $_REQUEST['groupBuyId'];
        $token = get_token();

        // 查询团购信息的参与人
        $partyList = M($this->model['name'])->where('token = "' . $token . '" and group_buy_id = ' . $groupBuyId)->select();
        $this->ajaxReturn($partyList);
    }

    /**
     * 增加组团优惠字段
     */
    private function addListGroupBuyField($listData)
    {
        $result = array();
        foreach ($listData as $item) {
            $partyInfo = M('groupbuy_party')->where(array("id" => $item['id']))->find();
            $groupBuyInfo = R('Addons://GroupBuy/GroupBuy/getGroupBuyInfo', array($partyInfo["groupbuy_info_id"]));
            $item['privilege'] = $groupBuyInfo["privilege"];
            array_push($result, $item);
        }

        $this->model = $this->getModel('groupbuy_party');

        // 返回
        return $result;
    }
}