<?php
/**
 * Created by PhpStorm.
 * User: wuhanchu
 * Date: 15/12/20
 * Time: 10:40
 */

namespace Addons\GroupBuy\Controller;


class GroupBuyTypeController extends BaseController {

    /**
     * init
     */
    function _initialize()
    {
        parent::_initialize();

        // 配置模型
        $this->model = $this->getModel('groupbuy_type');
    }

    /**
     * @param null $model
     * @param int $page
     * @param string $order
     * @return mixed
     */
    public function _get_model_list($model = null, $page = 0, $order = 'id desc',$showPrivilege = false)
    {
        $list_data = parent::_get_model_list($model, $page, $order); // TODO: Change the autogenerated stub
        $list_data ['list_data'] = $this->convertListField($list_data ['list_data'], 'payitem_id', 'payitem_id', 'school_payitem', 'id',name);

        return $list_data;
    }

    /**
     * 扩展字段下拉框
     * @param $fields
     * @return \Addons\School\Controller\Common\Controller\当前的字段
     */
    public function getFieldList($fields)
    {
        $fields = parent::getFieldList($fields);
        $fields = $this->setFiledExtra($fields, "payitem_id", 'school_payitem', 'name');

        // 返回
        return $fields;
    }
}