CREATE TABLE IF NOT EXISTS `wp_school` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`contribution`  text  COMMENT '驾校简介',
`photo`  int(10) UNSIGNED  COMMENT '照片',
`condition`  varchar(100)  COMMENT '基本条件',
`sign_info`  text  COMMENT '报名信息',
`phone`  int(20)  COMMENT '电话',
`name`  varchar(20) NOT NULL  COMMENT '名称',
`public_id`  varchar(100) NOT NULL  COMMENT '公众号ID',
`qq`  varchar(255)  COMMENT 'QQ',
`address`  varchar(255)  COMMENT '地址',
`recruit_place`  varchar(255) NOT NULL  COMMENT '招生地点',
`flow_info`  text  COMMENT '学车流程',
`contact`  varchar(255)  COMMENT '联系人',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_school` (`id`,`recruit_place`,`public_id`,`phone`,`name`,`contribution`,`condition`,`photo`,`qq`,`address`,`contact`,`sign_info`,`flow_info`) VALUES ('6','111','sdfas','1827301999','东正','','1,2','0','1192863020','111','张市强','','');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('school','驾校','0','','1','{"1":["photo","name","contact","phone","qq","contribution","condition","recruit_place","address","learn_flow","sign_info"]}','1:基础','','','','','name:名称\r\naddress:地址\r\nphone:电话\r\nrecruit_place:招生地点\r\nid:操作:[EDIT]|编辑,[DELETE]|删除,show&id=[id]|预览','10','','','1431512463','1432367590','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('contribution','驾校简介','text','editor','','','1','','0','0','1','1432021512','1431512717','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('photo','照片','int(10) UNSIGNED','picture','','','1','','0','0','1','1431656195','1431512527','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('condition','基本条件','varchar(100)','checkbox','','','1','1:可夜间练车\r\n2:可接送\r\n3:可刷卡\r\n4:是否速成\r\n5:可考自动档\r\n6:可分期','0','0','1','1431656205','1431512631','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('sign_info','报名信息','text','editor','','','1','','0','0','1','1432366116','1432366116','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('phone','电话','int(20)','num','','','1','','0','1','1','1431659631','1431512560','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','名称','varchar(20) NOT NULL','string','','','1','','0','1','1','1431512495','1431512495','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('public_id','公众号ID','varchar(100) NOT NULL','string','','','0','','0','0','1','1431681448','1431575143','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('qq','QQ','varchar(255)','string','','','1','','0','0','1','1431656189','1431575167','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('address','地址','varchar(255)','string','','','1','','0','0','1','1431656181','1431593833','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('recruit_place','招生地点','varchar(255) NOT NULL','string','','','1','','0','0','1','1431575108','1431575108','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('flow_info','学车流程','text','editor','','','1','','0','0','1','1432367504','1432367504','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('contact','联系人','varchar(255)','string','','','1','','0','0','1','1432211535','1432211535','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;