<?php
/**
 * Created by PhpStorm.
 * User: wuhanchu
 * Date: 15/11/11
 * Time: 15:56
 */

namespace Addons\Student\Controller;
use Addons\School\Controller\Common\Log\LogController;
use Addons\EO2OPayment\Controller\EO2OPaymentController;
use Addons\School\Controller\Common\Log\LogMajorType;

class DetailController extends StudentBaseController{
    /**
     * init
     */
    function _initialize()
    {

        parent::_initialize();
        $action = strtolower(_ACTION);

        // 子导航
        $param = array('student_id' => $_REQUEST['student_id']);

        $res ['title'] = '日志';
        $res ['url'] = addons_url('Student://Detail/log',$param);
        $res ['class'] = ($action == 'log') ? 'cur' : '';
        $nav [] = $res;

        $res ['title'] = '划款信息';
        $res ['url'] = addons_url('Student://Detail/moneyLog',$param);
        $res ['class'] = ($action == 'moneylog') ? 'cur' : '';
        $nav [] = $res;

        // assign
        $this->assign('sub_nav', $nav);
    }

    /**
     * 设置model对象
     */
    protected function setAdminModel()
    {
        // 选择表格模型
        switch($_REQUEST['info']){
            case "log":
                $this->model = $this->getModel('school_log');
                break;
            case "moneyLog":
                $this->model = $this->getModel('eo2o_payment');
                break;
            default:
                break;
        }

        parent::setAdminModel(); // TODO: Change the autogenerated stub
    }

    public function listsAdmin()
    {
        // 选择表格模型
        switch($_REQUEST['info']){
            case "log":
                $this->log();
                break;
            case "moneyLog":
                $this->moneyLog();
                break;
            default:
                break;
        }
    }


    /**
     * 学员的日志
     */
    function log(){
        $_REQUEST['major_type'] = LogMajorType::STUDENT;
        $_REQUEST['major_id'] = $_REQUEST['student_id'];
        $logController = new LogController();
        if($this->isAdmin()){
            $logController->listsAdmin();
        }else{
            $logController->lists();
        }
    }

    public function getModelInfo($ajaxReturn = true)
    {
        if(i("info") == "log"){
            $this->model = $this->getModel('school_log');

        }else if(i("info") == "moneyLog"){
            $this->model = $this->getModel('eo2o_payment');
        }

        return parent::getModelInfo($ajaxReturn); // TODO: Change the autogenerated stub
    }


    /**
     * 学员的划款流水
     */
    function  moneyLog(){
        $where = 'id  = ' .  $_REQUEST['student_id'] . '';
        $student = M("student")->where($where)->find();


        $paymentController = new EO2OPaymentController();

        if($this->isAdmin()){
            $map = "token = '".get_token()."' and result_code = 'SUCCESS' and (student_id = ".$student['id'];
            if(!empty($student['openid'])){
                $map .=" or openid = '".$student['openid']."')";
            }else{
                $map .=")";
            }
            $paymentController->listsAdmin(true,$map);
        }else{
            $_REQUEST['openid'] = $student['openid'];
            $nav = $this->get('nav');
            $subNav = $this->get('sub_nav');
            $paymentController->lists($nav,$subNav);
        }
    }
}